### ISSUE TITLE
Startup not working

### ISSUE THREAD

**Issue by kcteam** [JustYuuto/Yuuto-Stealer#10]
Dear bro !
Startup file after run about 160Mb , and can't start because error ffmpeg.dll
![Screenshot_2](https://github.com/JustYuuto/Yuuto-Stealer/assets/19942811/7d866345-9a02-4e90-9683-c185f046cb8d)

**Comment by kcteam** [comment]
And webhook not working too :(

**Comment by JustYuuto** [comment]
> Dear bro !
> Startup file after run about 160Mb , and can't start because error ffmpeg.dll
> ![Screenshot_2](https://github.com/JustYuuto/Yuuto-Stealer/assets/19942811/7d866345-9a02-4e90-9683-c185f046cb8d)
> 

The file inside the "win-extracted" folder ? 💀💀

**Comment by kcteam** [comment]
> 

in shell:startup bro , only one file

**Comment by JustYuuto** [comment]
I forgot about how electron is made 🗿
I'll resolve the thing when I can do it
