### ISSUE TITLE
Webhook / Stealer doesnt seem to work?

### ISSUE THREAD

**Issue by votexxd** [JustYuuto/Yuuto-Stealer#11]
Hi,

i started the build.bat file and answered all the questions but when i start the created executable nothing really happens. 
When starting the exe created in "dist" at first it says its "installing" something and then it wants to me start an exe as admin and thats it.
I see it running 3 times in the Task Manager but nothing is being send to the Webhook. Even double tripple checked the link.
Also, when i turn on the fake error message, nothing appears.

The OS im testing it on is Windows 11.
I installed Node.js, Python and Visual Studio with the "Desktop Development with C++" workload.

Another question. Why can i only select the stealing of Twitter, Reddit and Steam but not Roblox and Minecraft sessions?
Therewas also no option to steal browser stuff and if wanted to get os info etc.
Just wondering why so many Features were missing in the build file.

**Comment by byronbonkers** [comment]
I run the exe on my own pc and it adds itself to startup and runs 3 different versions in task manager and it doesn't send anything in the discord

**Comment by JustYuuto** [comment]
> I run the exe on my own pc and it adds itself to startup and runs 3 different versions in task manager and it doesn't send anything in the discord

It already took several minutes to retrieve all the things for me, how long did you wait?

**Comment by byronbonkers** [comment]
around 3 mins, i have rebuilt it and run it again and it is still running but hasn't sent anything, can I add u on discord for easier communication pls

**Comment by JustYuuto** [comment]
> around 3 mins, i have rebuilt it and run it again and it is still running but hasn't sent anything, can I add u on discord for easier communication pls

Yuuto#2106

**Comment by JustYuuto** [comment]
Should be fixed with the latest version
