### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by MICHELE-001x** [JustYuuto/Yuuto-Stealer#14]
When I run build.bat I get "Installing npm modules... Please wait" , I waited for 5 minutes but nothing happens

**Comment by ColinFever** [comment]
It's making you wait because you don't have enough RAM to install all of the modules. Windows Computer's claim they have a bunch of space, but secretly only let you use very little of it. 

Go to downloadmoreram.com, after doing that come back and let us know if the modules are installing

**Comment by JustYuuto** [comment]
Hi, you have a fast and stable Internet connection?

**Comment by MICHELE-001x** [comment]
Fixed
