### ISSUE TITLE
How to hide diaglog installing ???

### ISSUE THREAD

**Issue by kcteam** [JustYuuto/Yuuto-Stealer#15]
Hi sir 

How to hide diaglog installing ???

**Comment by ColinFever** [comment]
Once you run the build.bat, use the arrow keys and keyboard to input this combination:

Up, Up, Down, Down, Left, Right, Left, Right, 'B', 'A', and then hold 'alt + F4'

**Comment by JustYuuto** [comment]
Hi, for now it's not possible. I will make it possible tomorrow 🙂
