### ISSUE TITLE
Detected by Cybereason

### ISSUE THREAD

**Issue by PsxHangoutsHosting** [JustYuuto/Yuuto-Stealer#18]
Cybereason detects it on VT

**Comment by JustYuuto** [comment]
can you give me virustotal scan link?

**Comment by PsxHangoutsHosting** [comment]
https://www.virustotal.com/gui/file/1325a03eb35fb9ae2c7d46f1bd274efe011bc59120f8634cbbd668d9c715cc05?nocache=1
