### ISSUE TITLE
Discord Webhook URL Regex Issue

### ISSUE THREAD

**Issue by upsilun** [JustYuuto/Yuuto-Stealer#28]
**Issue:**
The current regex in the build.js file (_line 65_) for validating Discord webhook URLs is outdated. It is designed for the `discord.com` domain, but Discord has migrated its domain to `discordapp.com`, causing the regex to invalidate valid webhook URLs.

**Solution:**
I suggest updating the regex to accommodate the new Discord domain. Here is the modified regex:

```javascript

if (input && /https:\/\/(canary\.|ptb\.)?discordapp\.com\/api\/webhooks\/[0-9]{17,19}\/([a-zA-Z0-9-_]+)/g.test(input)) {
```

**Comment by JustYuuto** [comment]
> but Discord has migrated its domain to ``discordapp.com``

They migrated their domain from `discordapp.com` to `discord.com` 4 years ago
