### ISSUE TITLE
what the actual fuck are these exes

### ISSUE THREAD

**Issue by Firoxus** [JustYuuto/Yuuto-Stealer#29]
okay so basically where the fuck are there 2 .exe files that get flagged by 34 avs as a logger???
also they are named decrypt_token.exe and something else and they dont even get used in the code?

**Comment by JustYuuto** [comment]
Forgot to remove them, sorry

**Comment by TNEGA69** [comment]
> okay so basically where the fuck are there 2 .exe files that get flagged by 34 avs as a logger??? also they are named decrypt_token.exe and something else and they dont even get used in the code?

Bitte mach ein Comeback. Ich habe einen Plan.

**Comment by TNEGA69** [comment]
Bitte join https://discord.gg/5gthmmPwat
~Indian Tek Support

**Comment by TNEGA69** [comment]
ok
