### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by sharifjameel90** [JustYuuto/Yuuto-Stealer#7]
Hi im trying to log only discord token and im not good at doing regex i need some help to log the victim discord token
is there any possibility that u can provide me some code on only logging victim token?

**Comment by JustYuuto** [comment]
Hi, the code I use to get victim's Discord token is located in the file https://github.com/JustYuuto/Grabber/blob/master/functions/grab-discord-token.js. The file is undocumented but I think you'll recognize some elements/functions I use to get the token, like the paths, the token validation, etc. If you have questions don't hesitate to ask them

**Comment by sharifjameel90** [comment]
Thanks i did understand the code I'm unable to reproduce code and results
