### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by kixx007** [JustYuuto/Yuuto-Stealer#8]
help me 
![Capture](https://github.com/JustYuuto/Yuuto-Stealer/assets/89723323/418b91da-db8f-494d-b8f9-869a6db9c16e)

**Comment by JustYuuto** [comment]
You need to run ``npm install`` before running the building script, I forgot to put the command in the docs sry 💀

**Comment by kixx007** [comment]
bro dont send to webhook, i had config

**Comment by lugreo** [comment]
be careful he is a scammer, I have paid him and he has blocked me from telegram
